### ISSUE TITLE
Gaming Society is unclear - change to Video Gaming or Computer Gaming society?

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website-old#31]
The top navbar text is perhaps unclear on what the society actually does?

We do all kinds of video and computer gaming - not just general gaming - could be confused for table top games, card games etc... It was also suggested to make this **BOLD** in the first paragraph to make it clear.

![image](https://user-images.githubusercontent.com/8648058/45258288-01759f80-b3ad-11e8-98fb-f33444c45b64.png)

First paragraph text could also be clarified - there may be other locations that need this edit: 

![image](https://user-images.githubusercontent.com/8648058/45258332-a0020080-b3ad-11e8-8bc0-7ecaee6a41e6.png)

**Comment by boardfish** [comment]
Wording flows better if we don't specify every time. Does more need to be done to show ourselves as a *video* gaming society, or can we safely rely on the assumption that they'll know?

**Comment by Aterfax** [comment]
Depends if you assume new people will read throughly / are already members?
