### ISSUE TITLE
SLUGSoc within text should ideally stick to the existing UI theming i.e. SLUGSoc not SLUGSOC.

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website-old#32]
In some places the text doesn't conform to the existing UI style of SLUGSoc.

e.g.

![image](https://user-images.githubusercontent.com/8648058/45258310-50233980-b3ad-11e8-8254-3329368cdc79.png)

We should probably also ensure we refer to SLUGSoc rather than SLUGS to prevent confusing new people.

We talk about SLUGSoc, then SLUGS. Is SLUGS the same? Are members called SLUGS etc... could be confusing.

**Comment by boardfish** [comment]
This one's a weird line to walk. Both internally and externally for the most part we call ourselves SLUGS both as a society and as members, but the domain name itself is slugsoc.co.uk. I think I'll standardise to SLUGS.

**Comment by Aterfax** [comment]
So long as it standardises to something and it remains clear it's fine.
