### ISSUE TITLE
SLUGSoc at a glance is actually SLUGSoc events at a glance.

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website-old#34]
User fed back that they expected SLUGSoc at a glance to be a brief explanation of what SLUGSoc is, what they do, what they offer them, how much it costs etc....

At present this shows what SLUGSoc events are happening shortly.

We could do with adding this as a element in situ next to the events stream:

![image](https://user-images.githubusercontent.com/8648058/45258409-d3915a80-b3ae-11e8-8db8-8a986d8df547.png)

i.e. split this into two boxes, one with events, one with a quick explanation of SLUGSoc?

**Comment by boardfish** [comment]
This could be another section of the site if absolutely necessary, but I think the description at the top covers it. Either way, leaving this issue up so I can change the heading to Events rather than SLUGSoc.
