### ISSUE TITLE
Move socials to front of navbar order

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website-old#36]
User feedback:

> The view details links for socials and lan events do not match the order of the section headings. I'd expect lan events to be listed before socials there.Then for the banner at the top to go about lans, socials, then our committee.
> It keeps the order of lan then social intact. It might be worth altering the first text to also talk about lans before socials.
>

**Comment by Aterfax** [comment]
Irrespective of what optional order is chosen - the order should remain consistent!

**Comment by boardfish** [comment]
I'll move Socials up the order.
