### ISSUE TITLE
Text is difficult to read.

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website-old#37]
![image](https://user-images.githubusercontent.com/8648058/45258460-d0e33500-b3af-11e8-97ed-0ddeaa2dfd90.png)

**Comment by Aterfax** [comment]
The opacity of the boxes with text in probably needs to be increased to make text easier to read.

**Comment by boardfish** [comment]
No separation was a design choice.

**Comment by Aterfax** [comment]
Fair, might be a choice but I still think it looks odd due to the offset to the increased opacity boxes.
