### ISSUE TITLE
Competitive box has a Discord link in it?

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website-old#40]
User feedback: 

> Why's that there?

![image](https://user-images.githubusercontent.com/8648058/45258520-12281480-b3b1-11e8-9c9a-17d9b90bc4f9.png)

**Comment by boardfish** [comment]
Line above the button. That said, I'd perhaps suggest making this a direct link to the nuel channel...but our server structure doesn't really allow for that, unfortunately. Closing.
