### ISSUE TITLE
Two identical sections for LANs?

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website-old#43]
User feedback:

> Why are there two sections on the same page for LANs?

I think they mean these?

![image](https://user-images.githubusercontent.com/8648058/45258583-f8d39800-b3b1-11e8-89ef-84f2145915e7.png)

![image](https://user-images.githubusercontent.com/8648058/45258589-0ee15880-b3b2-11e8-9e53-1fbb6957c961.png)

**Comment by boardfish** [comment]
The first section links to the LAN event if it's in the system. The second is something @Lauriestar said she liked, and it's probably helpful for the more uneasy newcomers to market us as a welcoming soc. Closing, but I'll reopen if you have further questions.
