### ISSUE TITLE
About LAN Events paragraph needs tweaking:

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website-old#47]
![image](https://user-images.githubusercontent.com/8648058/45258708-78fafd00-b3b4-11e8-9429-26aa0e3cbfc7.png)

"We've run over 70 LAN events here at SLUGSoc. They're normally hosted at the Ridge building on Ranmoor student village, giving our players free rein to set up their gear and adventure together across an assortment of games. LAN favourites include Quiplash 2, Mario Kart 8 Deluxe, Overwatch and Guns of Icarus."

Run =/= **Ran**

Ranmoor student village =/= **Ranmoor Student Village**

Entire section needs rework - 

User Feedback:

> I'm fine up until "giving our players... How does that phrase relate to the first bit to be joined by a comma? What's special about the ridge that you have free rein there but not elsewhere?
> 
> The text here can't just be gobbledegook! It needs to be carefully checked that it both reads well, makes sense, and is factually accurate.
> 
> Since when was quiplash 2 a lan favourite? Plus, so much the favourite that it's first on that list. I'd say league or some other crap like that belongs there before that. Same for mario kart 8 and guns of icarus.

> Why doesn't that paragraph mention anything critical either like there being fast internet or a tuck shop?
> What about the lan playlist? Pub quiz? In the end it's a somewhat bland description  that unless you like those 4 games doesn't hype you for anything else.
> 
> What's a lan - unless you really understand what a LAN connection is that's not so useful. I'd change that to where computers are hooked up together to allow for multiplayer gaming or something like that.
> Stay away from technical definitions or move that onto the right. Or put it in quotation marks to make it clear those aren't our words.
> 
> Again with the font sizing lan rules, the rule headings - again, the font size changes!
> 
> Bring your console/desktop pc? but no laptops?
> 
> Favourite games with friends => old friends and new!
> 
> "that aside" <- remove, that suggests the text before it isn't important, which it totally is!
> 
> The details in this paragraph should really be mixed in with the one before, it makes lans sound 10x more awesome the the first paragraph.
> 
> These are important, so they should be easy to read, not harder!
> 
> I find the narrow text difficult to read.
> *narrow font
>

**Comment by Aterfax** [comment]
> 
> 
>"Please do not bring extension leads, as our power network is very carefully worked out so that we don't short out the venue or cause a fire! We provide everyone with two power sockets (one for a monitor and one for a PC/console), so you shouldn't need one." => "Please do not bring extension leads! We provide everyone with two power sockets (one for a monitor and one for a PC/console), so you shouldn't need one. Our power network is carefully worked out so that everyone has enough electricity and nothing overloads, causing a fire."
> 
> illegal => piracy => software piracy,
> 
> 
> Maybe include a link or condensed version of cics's internet usage rules
> 
> Only use two sockets => merge into bring extension leads
>

**Comment by Aterfax** [comment]
> Also thinking about it technically consumption of alcohol isn't illegal.
> 
> So why's that under the don't do anything illegal heading?

**Comment by boardfish** [comment]
Raising separate issue for LAN rules, #54. Deleted comments are now in that issue.

**Comment by boardfish** [comment]
Everything here is valid besides the run-on sentence and 'ran'.

'Have run' is [grammatically correct](https://languageandgrammar.com/2008/06/18/have-you-run-into-this-grammar-error/).

>They're normally hosted at the Ridge building on Ranmoor student village, giving our players free rein to set up their gear and adventure together across an assortment of games.

Can be paraphrased as 'We host LANs (...). This gives our players free rein to set up their gear...' You're right, there's nothing special about the Ridge in that sentence, but the run-on makes sense because the fact that we host LANs at all gives our players free rein, etc.

**Comment by boardfish** [comment]
Also, whoever your source is, I can't say I appreciate this:

>The text here can't just be gobbledegook! It needs to be carefully checked that it both reads well, makes sense, and is factually accurate.

I gave it my best effort.

**Comment by boardfish** [comment]
Also...

>Since when was quiplash 2 a lan favourite? Plus, so much the favourite that it's first on that list. I'd say league or some other crap like that belongs there before that. Same for mario kart 8 and guns of icarus.

Quiplash 2 has been a LAN favourite for at least the last five LANs. We always play it on break before the pub quiz answers get revealed, and it's a laugh.

As for the rest, there's no definite favourite as we have such diverse tastes, but everything listed gets a decent following.

**Comment by guruthree** [comment]
Apologies for the "gobbledegook", and do I appreciate the effort that's gone in. 2AM isn't really an excuse, but reading it I just didn't feel it captured the magic of our LANs.

As for the games being played, maybe I don't sit next to the right people? Even then, I definitely don't remember there being that much Quiplash. I would  argue that at the very least it doesn't belong first on the list as it's not a traditional PC game, although it is a fun LAN event.

**Comment by guruthree** [comment]
Perhaps something like this for the text:

We've run over 70 LAN events here at SLUGSoc. We setup power and super-fast gigabit internet to over 60 seats and give our players a great time playing a variety of games! LAN favourites include Overwatch, Dota 2, Left 4 Dead 2, Rainbow 6 Siege, Guns of Icarus, League of Legends, Warframe, Quiplash 2, Super Smash Brothers, and Mario Kart 8 Deluxe.

If you've never been to a LAN before, look forward to a fun weekend of gaming! Bring your desktop/laptop/console and get ready to enjoy your favourite games with friends. 

LANs are normally hosted at the Ridge building on Ranmoor Student Village, a great Sheffield location just past Broomhill and central to most student accommodation. Attendees get a meter of desk to set up their gear, along with internet access and two plug sockets. Other LAN benefits include our 24/7 tuck shop for midnight-munchies, a non-stop LAN playlist for tunes, quiet rooms for a nap, a pub-quiz, and Saturday pizza order. Come and join us!

**Comment by boardfish** [comment]
I think you've worded it better than I tried to. I'll try and copy that in for the most part with some amendments.
