### ISSUE TITLE
Amend LAN rules

### ISSUE THREAD

**Issue by boardfish** [SLUGSoc/website-old#54]
@Aterfax:

    "Please do not bring extension leads, as our power network is very carefully worked out so that we don't short out the venue or cause a fire! We provide everyone with two power sockets (one for a monitor and one for a PC/console), so you shouldn't need one." => "Please do not bring extension leads! We provide everyone with two power sockets (one for a monitor and one for a PC/console), so you shouldn't need one. Our power network is carefully worked out so that everyone has enough electricity and nothing overloads, causing a fire."

    illegal => piracy => software piracy,

    Maybe include a link or condensed version of cics's internet usage rules

    Only use two sockets => merge into bring extension leads

**Comment by boardfish** [comment]
Also thinking about it technically consumption of alcohol isn't illegal.

    So why's that under the don't do anything illegal heading?

**Comment by boardfish** [comment]
> Only use two sockets => merge into bring extension leads

We need to draw attention to both. They shouldn't be able to bring extension leads and they should be aware they'll only have two ports at their disposal.

> So why's [comsumption of alcohol] under the don't do anything illegal heading?

Because the premises are unlicensed and we aren't insured, so it's both illegal and could come at a cost to us.

> software piracy

That's not broad enough. They might think this excuses pirating films on the network. We need to stay vigilant of all of it.

**Comment by guruthree** [comment]
Can we flip the order slightly so that Don't do anything illegal is first? This puts the three power-related rules next to each other.

For me, when first loading the page the first rule is expanded. Is this the default? If so, I think it would be better if no rule was expanded at first so that they draw equal attention.

**Comment by Aterfax** [comment]
Unlicensed premises does not make drinking illegal. It would however put all culpability/responsibility on the drinker and/or organisation allowing it to occur.

Illegal activity being forbidden is clear enough - giving examples of specific stuff that counts such as copyright theft is fine.

Still needs rewording.

**Comment by boardfish** [comment]
All current feedback addressed for this issue in:

- [b4b3c94](https://github.com/SLUGSoc/website/commit/b4b3c944771b2743f4a154cdb009466d727e9782)
- [ec70ff7](https://github.com/SLUGSoc/website/commit/ec70ff754db190e3f4dec5289d865aa09365ceb8)
- [edd4cf4](https://github.com/SLUGSoc/website/commit/edd4cf4d0a51b9395944b7e586db194697148f31)

Closing.
